# This file gives explicit instructions to the deployment server.

[phases.setup]
# Tell the server to install Java 8 and Maven.
nixPkgs = ["pkgs.jdk8", "pkgs.maven"]

[phases.build]
# Tell the server exactly how to build the project.
cmds = ["mvn clean install -DskipTests"]

[start]
# Tell the server exactly how to start the application after building it.
cmd = "java -jar target/client-management-system-1.0.0.jar"